export { default as Dashboard } from "./dashboard/DashboardScreen";
export { default as PageNotFound } from "./error/PageNotFound";
export { default as Karyawan } from "./karyawan/KaryawanScreen";
export { default as AdminLogin } from "./adminlogin/AdminLoginScreen";
export { default as UserHome } from "./user/UserHome";
export { default as UserRegistrasi } from "./user/UserRegistrasi";
export { default as UserLogin } from "./user/UserLogin";
export { default as UserAbsen } from "./user/UserAbsen";
export { default as UserLoading } from "./user/UserLoading";